class AuthError(Exception):
    pass


class ValueNotFoundError(Exception):
    pass
